export default {
  toggleTheme: "toggleTheme",
  setValueEditor: "setValueEditor",

  APPOINTMENTS: {
    LAYOUT_TYPE_APPOINTMENT: "LAYOUT_TYPE_APPOINTMENT",
    REFETCH_LIST_APPOINTMENT: "REFETCH_LIST_APPOINTMENT",
    CURRENT_EDITING_APPOINTMENT: "CURRENT_EDITING_APPOINTMENT",
    LIST_DOCTOR: "LIST_DOCTOR",
    LIST_PATIENT: "LIST_PATIENT",
    PENDING_APPOINTMENT: "PENDING_APPOINTMENT",
    DURATION_LIST: "DURATION_LIST",
  },

  AUTHENTICATION: {
    REFRESH_TOKEN: "REFRESH_TOKEN",
    USER_INFOS: "USER_INFOS",
  },

  LAYOUT: {
    SIDE_BAR_WIDTH: "SIDE_BAR_WIDTH",
  },

  DOCTOR: {
    REFETCH_LIST_DOCTOR: "REFETCH_LIST_DOCTOR",
  },

  PATIENT: {
    REFETCH_LIST_PATIENT: "REFETCH_LIST_PATIENT",
  },
};
