export default {
  toggleTheme: "toggleTheme",
  setValueEditor: "setValueEditor",

  APPOINTMENTS: {
    LAYOUT_TYPE_APPOINTMENT: "LAYOUT_TYPE_APPOINTMENT",
    REFETCH_LIST_APPOINTMENT: "REFETCH_LIST_APPOINTMENT",
    CURRENT_EDITING_APPOINTMENT: "CURRENT_EDITING_APPOINTMENT",
    LIST_DOCTOR: "LIST_DOCTOR",
    LIST_PATIENT: "LIST_PATIENT",
  },

  AUTHENTICATION: {
    REFRESH_TOKEN: "REFRESH_TOKEN",
    USER_INFOS: "USER_INFOS",
  },
};
