export default {
  toggleTheme: "toggleTheme",
  setValueEditor: "setValueEditor",

  APPOINTMENTS: "APPOINTMENTS",
  OPEN_CREATE_APPOINTMENT: "OPEN_CREATE_APPOINTMENT",
  CURRENT_DATE_APPOINTMENT: "CURRENT_DATE_APPOINTMENT",
};
